### ISSUE TITLE
Meeting type - Open and Closed - Need to update description text

### ISSUE THREAD

**Issue by TheSoberJewel** [CAWSCIT/ca-meeting-finder-issue-tracker#22]
**Describe the bug**
When looking at any specific meeting info that is in the Meeting Type category of Open or Closed, when the user clicks on the question mark button to get more info, the text of both the Open and the Closed meeting types state 'Alcoholics Anonymous' and contain other AA related language.  Please review all instances where text was copy/pasted from code provided by the AA developers and update the text reflect 'Cocaine Anonymous,' 'addict(s),' etc.

**To Reproduce**
1. Filter by Meeting Type - Open or Closed
2. Click on any meeting
3. Click on question mark by Open or Closed

**Expected behavior**
Expect to see all 'canned' language to be Cocaine Anonymous specific.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE 5G
 - OS: Android ver 13

**Additional context**

**Comment by enderv** [comment]
Thanks for the report! Just a note for whoever gets to it: https://github.com/code4recovery/tsml-ui/tree/main?tab=readme-ov-file#override-type-descriptions

**Comment by enderv** [comment]
should be fixed now

**Comment by enderv** [comment]
This was the default from the upstream project. will open a new issue to see if we want to replace the description with anything

**Comment by enderv** [comment]
This is still happening in other languages

**Comment by KalobTaulien** [comment]
Thank you for re-opening this, @enderv! 

More details below: 
I believe this came up as french still shows `... des Alcooliques anonymes ...`. 
![image](https://github.com/user-attachments/assets/1fc2b409-7664-4051-8a28-234fa6bd37fd)
That comes from here: https://github.com/code4recovery/tsml-ui/blob/main/src/i18n/fr.ts#L73

Our repo (for developers) shows we've undefined this: https://github.com/CAWSCIT/ca-mobile-app/blob/master/meetings.html#L22-L27. 

It looks like we're also missing 2 supported TSML UI languages (`nl` and `pt`) from https://github.com/code4recovery/tsml-ui/blob/main/src/helpers/settings.ts#L77-L85
